### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by zramsay**
- deduplicates a file like this that is in a bunch of repos. The README of each repo should have a section that just links to this file, rather than maintain a seperate file in each repo

### CODE REVIEW

**Comment by adrianbrink** [comment]
We need a code of conduct in every repo in order to fulfil github's community standards.

https://github.com/tendermint/basecoin/community

vs

https://github.com/tendermint/ethermint/community

**Comment by zramsay** [comment]
ugh, ok. What if we just have a code of conduct page who's only content links to this repo?

**Comment by adrianbrink** [comment]
That would work. But generally speaking I don't see the major problem in having a separate code of conduct. It is not a living document. We decided once and it remains unchanged. In my mind it is the same as the license files in the repos.

**Comment by zramsay** [comment]
yeah and it's only in a few repos tops anyways. ok, we don't need it in here.

**Pull request closed without merging**
